# Generated by Django 5.1.3 on 2024-11-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsetting',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
